TranApp/Models/PurchaseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TranApp.Models
{
    public class PurchaseViewModel
    {
        public int UserId { get; set; }

        [Required(ErrorMessage = "harus diisi.")]
        [Display(Name = "Product Id")]
        public int ProductId { get; set; }

        public string ProductName { get; set; }

        [Required(ErrorMessage = "harus diisi.")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        public DateTimeOffset PurchaseDate { get; set; }
    }
}

TranApp/Pages/Purchase/DeletePurchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TranApp.Enums;
using TranApp.Models;
using TranApp.Services;

namespace TranApp.Pages.Purchase
{
    [Authorize(Roles = UserRoles.Admin + ", " + UserRoles.User)]
    public class DeletePurchaseModel : PageModel
    {
        private readonly TranAppService _tranAppMan;
        private readonly IDataProtector _protector;

        public DeletePurchaseModel(TranAppService tranAppService, IDataProtectionProvider provider)
        {
            this._tranAppMan = tranAppService;
            this._protector = provider.CreateProtector("TranAppProtector");
        }

        [BindProperty(SupportsGet = true)]
        public string ProtectedData { get; set; }

        [BindProperty(SupportsGet = true)]
        public PurchaseViewModel Form { set; get; }

        public async Task<ActionResult> OnGetAsync()
        {
            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._tranAppMan.GetLogin(userNameLogin)).UserId;

            Form.ProductId = Convert.ToInt32(_protector.Unprotect(ProtectedData));

            Form = await _tranAppMan.GetPurchaseByProductId(Form.ProductId, userIdLogin);

            if (Form == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._tranAppMan.GetLogin(userNameLogin)).UserId;

            Form = await _tranAppMan.GetPurchaseByProductId(Form.ProductId, userIdLogin);

            await _tranAppMan.DeleteCart(Form.ProductId, Form.UserId);
            return RedirectToPage("/Purchase/Index");
        }
    }
}

TranApp/Pages/Purchase/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TranApp.Enums;
using TranApp.Models;
using TranApp.Services;

namespace TranApp.Pages.Purchase
{
    [Authorize(Roles = UserRoles.Admin + ", " + UserRoles.User)]
    public class IndexModel : PageModel
    {
        private readonly TranAppService _tranAppMan;
        private readonly IDataProtector _protector;

        public List<PurchaseCartModel> Purchases { get; set; }

        public PurchaseViewModel Pesanan { get; set; }
        [TempData]
        public string SuccessMessage { get; set; }

        public IndexModel(TranAppService tranAppService, IDataProtectionProvider provider)
        {
            this._tranAppMan = tranAppService;
            this._protector = provider.CreateProtector("TranAppProtector");
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var findLogin = await this._tranAppMan.GetLogin(userNameLogin);

            await this._tranAppMan.FetchAllById(findLogin.UserId);
            this.Purchases = this._tranAppMan.Purchases;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var findLogin = await this._tranAppMan.GetLogin(userNameLogin);
            await this._tranAppMan.FetchAllById(findLogin.UserId);
            this.Purchases = this._tranAppMan.Purchases;

            var tanggalSekarang = DateTimeOffset.Now;

            foreach (var item in this.Purchases)
            {
                Pesanan = new PurchaseViewModel()
                {
                    UserId = item.UserId,
                    ProductId = item.ProductId,
                    ProductName = item.ProductName,
                    Quantity = item.Quantity,
                    PurchaseDate = tanggalSekarang
                };

                var result = await this._tranAppMan.InsertOrder(Pesanan);
                if (result == false)
                {
                    SuccessMessage = "Failed";
                    return Page();
                }

            };

            await this._tranAppMan.SaveToDatabase();

            return Page();
        }

        public IActionResult OnPostEdit(int UnProtected)
        {
            string tempUnProtected = UnProtected.ToString();
            string ProtectedData = _protector.Protect(tempUnProtected);

            return Redirect($"~/Purchase/UpdatePurchase/{ProtectedData}");
        }

        public IActionResult OnPostDelete(int UnProtected)
        {
            string tempUnProtected = UnProtected.ToString();
            string ProtectedData = _protector.Protect(tempUnProtected);

            return Redirect($"~/Purchase/DeletePurchase/{ProtectedData}");
        }
    }
}

TranApp/Pages/Purchase/InsertPurchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TranApp.Enums;
using TranApp.Models;
using TranApp.Services;

namespace TranApp.Pages.Purchase
{
    [Authorize(Roles = UserRoles.Admin + ", " + UserRoles.User)]
    public class InsertPurchaseModel : PageModel
    {
        private readonly TranAppService _tranAppMan;

        [BindProperty(SupportsGet = true)]
        public PurchaseViewModel Form { get; set; }

        [BindProperty(SupportsGet = true)]
        public List<ProductViewModel> ListProduct { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }

        public InsertPurchaseModel(TranAppService tranAppService)
        {
            this._tranAppMan = tranAppService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            ListProduct = await _tranAppMan.GetAllProduct();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var findLogin = await this._tranAppMan.GetLogin(userNameLogin);
            Form.UserId = findLogin.UserId;

            var checkProductExist = await _tranAppMan.CheckCartProductExist(Form);

            if (checkProductExist == false)
            {
                SuccessMessage = "Produk telah ada di keranjang belanja";
                return RedirectToPage();
            }

            var stock = await _tranAppMan.CheckStock(Form);

            if (stock == false)
            {
                SuccessMessage = "Permintaan melebihi Stock, mohon kurangi jumlah pembelian (Quantity) Anda";
                return RedirectToPage();
            }
            else
            {
                await _tranAppMan.InsertCart(Form);
            }


            return Redirect("/Purchase/Index");
        }
    }
}

TranApp/Pages/Purchase/UpdatePurchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TranApp.Enums;
using TranApp.Models;
using TranApp.Services;

namespace TranApp.Pages.Purchase
{
    [Authorize(Roles = UserRoles.Admin + ", " + UserRoles.User)]
    public class UpdatePurchaseModel : PageModel
    {
        private readonly TranAppService _tranAppMan;
        private readonly IDataProtector _protector;

        [BindProperty(SupportsGet = true)]
        public string ProtectedData { get; set; }

        public UpdatePurchaseModel(TranAppService tranAppService, IDataProtectionProvider provider)
        {
            this._tranAppMan = tranAppService;
            this._protector = provider.CreateProtector("TranAppProtector");
        }
        [BindProperty(SupportsGet = true)]
        public PurchaseViewModel Form { set; get; }


        public async Task<IActionResult> OnGetAsync()
        {
            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._tranAppMan.GetLogin(userNameLogin)).UserId;

            Form.ProductId = Convert.ToInt32(_protector.Unprotect(ProtectedData));

            Form = await _tranAppMan.GetPurchaseByProductId(Form.ProductId, userIdLogin);

            if (Form == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return BadRequest(ModelState);
            }
            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._tranAppMan.GetLogin(userNameLogin)).UserId;

            Form = new PurchaseViewModel()
            {
                UserId = userIdLogin,
                ProductId = Form.ProductId,
                Quantity = Form.Quantity
            };

            await _tranAppMan.UpdateCart(Form);
            return RedirectToPage("/Purchase/Index");
        }
    }
}

TranApp/Pages/Purchase/DeletePurchase.cshtml
@page "{ProtectedData}"
@model TranApp.Pages.Purchase.DeletePurchaseModel
@{
}

<h1>Delete Data Confirmation</h1>
<form method="post">
    <div>
        <h3>Apakah anda yakin untuk menghapus @Model.Form.ProductName ?</h3>
        <h3>:'(</h3>
    </div>
    <br />

    <input asp-for="Form.ProductId" readonly hidden />
    <input asp-for="Form.UserId" readonly hidden />
    <input asp-for="Form.ProductName" readonly hidden />
    <input asp-for="Form.Quantity" readonly hidden />

    <button type="submit">Delete</button>
</form>

TranApp/Pages/Purchase/Index.cshtml
@page
@model TranApp.Pages.Purchase.IndexModel
@{
}

<h1>Purchase List</h1>
<a href="~/Purchase/InsertPurchase">Insert</a>
<br />
<table border="1">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Product ID</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Purchase Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Purchases)
        {
            <tr>
                <td>@item.UserId</td>
                <td>@item.ProductId</td>
                <td>@item.ProductName</td>
                <td>@item.Quantity</td>
                <td>@item.PurchaseDate</td>
                <td>
                    <form asp-page-handler="edit" method="post">
                        <button class="btn btn-warning">Edit</button>
                        <input type="hidden" name="UnProtected" value="@item.ProductId" />
                    </form>
                    <form asp-page-handler="delete" method="post">
                        <button class="btn btn-danger">Delete</button>
                        <input type="hidden" name="UnProtected" value="@item.ProductId" />
                    </form>
                    @*<a href="~/Purchase/UpdatePurchase/@item.ProductId">Edit</a>*@
                    @*<a href="~/Purchase/DeletePurchase/@item.ProductId">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <form method="post">
        <button class="btn btn-primary" type="submit">Order</button>
    </form>
</div>

TranApp/Pages/Purchase/InsertPurchase.cshtml
@page
@model TranApp.Pages.Purchase.InsertPurchaseModel
@{
}

<h3>Insert Cart</h3>
<form method="POST">
    <div>
        Product Name: <select asp-for="Form.ProductId">
    @foreach (var item in Model.ListProduct)
    {
        @*<option value="@item.ProductId">@item.ProductName</option>*@
        <option value="@item.ProductId">@item.ProductName, Stock: @item.Stock</option>
    }
</select>
    </div>
    <div>
        <label asp-for="Form.Quantity"></label>
        <input asp-for="Form.Quantity" />
        <span asp-validation-for="Form.Quantity"></span>
    </div>
    <br />
    <button type="submit">Add to Cart</button>
</form>
<div>
    <p>@Model.SuccessMessage</p>
</div>

TranApp/Pages/Purchase/UpdatePurchase.cshtml
@page "{ProtectedData}"
@model TranApp.Pages.Purchase.UpdatePurchaseModel
@{
}

<form method="post">
    <div>
        <label asp-for="Form.UserId"></label>
        <input asp-for="Form.UserId" readonly disabled />
        <span asp-validation-for="Form.UserId"></span>
        <br />
        <label asp-for="Form.ProductId"></label>
        <input asp-for="Form.ProductId" readonly/>
        <span asp-validation-for="Form.ProductId"></span>
        <br />
        <label asp-for="Form.ProductName"></label>
        <input asp-for="Form.ProductName" readonly disabled />
        <span asp-validation-for="Form.ProductName"></span>
        <br />
        <label asp-for="Form.Quantity"></label>
        <input asp-for="Form.Quantity" />
        <span asp-validation-for="Form.Quantity"></span>
    </div>
    <div>
        <button type="submit">Update Cart</button>
    </div>
</form>